apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.networkShare.credentialsSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.networkShare.username }}
  password: {{ .Values.networkShare.password }}
  domain: {{ .Values.networkShare.domain }}