apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.networkShare.id }}-pvc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Release.Namespace }}-smb