apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.networkShare.storageClassName }}
provisioner: smb.csi.k8s.io
parameters:
  source: {{ .Values.networkShare.path | quote }}
  csi.storage.k8s.io/node-stage-secret-name: {{ .Values.networkShare.credentialsSecretName }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Values.networkShare.credentialsSecretNameSpace }}
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0