apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.id }}
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "{{ .Values.app.id }}-image-stream:latest",
            "namespace": "docker-experiments"
          },
          "fieldPath": "spec.template.spec.containers[?(@.name==\"my-container-name\")].image",
          "pause": "false"
        }
      ]
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app.id }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.id }}
    spec:
      containers:
        - name: {{ .Values.app.id }}
          image: "image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Values.app.id }}-image-stream:latest"
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_FILE_PATH
              value: "{{ .Values.app.configPath }}/{{ .Values.app.configFileName }}"
          startupProbe:
            httpGet:
              path: /health/live
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: {{ .Values.app.configPath }}
              readOnly: true
            - name: work-storage
              mountPath: {{ .Values.app.workStoragePath }}
            - name: network-share
              mountPath: {{ .Values.app.networkSharePath }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.app.id }}-config
        - name: work-storage
          emptyDir:
            sizeLimit: "500Mi"
        - name: network-share
          persistentVolumeClaim:
            claimName: {{ .Values.networkShare.pvcName }}