apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: network-share-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: simulated-network-share
  volumeName: network-share-pv