apiVersion: v1
kind: PersistentVolume
metadata:
  name: network-share-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: simulated-network-share
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
    - noperm
    - nounix
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: network-share-pv
    volumeAttributes:
      source: "//192.168.0.111/SimulatedNetworkShare"
    nodeStageSecretRef:
      name: network-share-credentials
      namespace: docker-experiments
