apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.serviceName }}
spec:
  selector:
    app: {{ .Values.db.deploymentId }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432