db:
  deploymentId: "docker-experiments-db"
  dbName: "DockerExperimentsDB"
  username: "admin"
  password: "password123"
  serviceName: "docker-experiments-db"
  image:
    repository: "registry.redhat.io/rhel8/postgresql-12"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  size: "1Gi"

networkShare:
  storageClassName: "network-share-storage-class"
  pvcName: "network-share-pvc"

app:
  id: "docker-experiments-app"
  gitSource: 
    uri: "https://github.com/TalBenZvi/Docker-Experiments.git"
    ref: "main"
  startupProjectFile: "DockerExperiments/DockerExperiments.WebAPI/DockerExperiments.WebAPI.csproj"
  configPath: "/app/config"
  configFileName: "appsettings.json"
  workStoragePath: "/mnt/work-storage"
  networkSharePath: "/mnt/network-share"
  

  