name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./DockerExperiments
          file: ./DockerExperiments/DockerExperiments.WebAPI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-experiments:${{ github.sha }}

      - name: Update Deployment Repository
        run: |
          git config --global user.name "gitops-bot"
          git config --global user.email "bot@yourdomain.com"
          
          git clone https://${{ secrets.GITOPS_GITHUB_TOKEN }}@github.com/TalBenZvi/Docker-Experiments-Deployment.git
          cd docker-experiments/templates/app
          
          sed -i "s|image: .*|image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/docker-experiments:${{ github.sha }}|g" deployment.yaml
          
          git add deployment.yaml
          git commit -m "Deploy: Update image to ${{ github.sha }}"
          git push
